name = "cf_ai_tos_whisperer"

main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_NAME = "ToS Whisperer"

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "USER_STATE", class_name = "UserState" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserState"]

# Optional: add a route when deploying to a zone
# [[routes]]
# pattern = "*/*"
# zone_name = "example.com"

[assets]
directory = "public"

[observability]
enabled = true
